/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import { Prisma, App, User, Category, Grade, Tag } from "@prisma/client";

export class AppServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.AppFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AppFindManyArgs>
  ): Promise<number> {
    return this.prisma.app.count(args);
  }

  async findMany<T extends Prisma.AppFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AppFindManyArgs>
  ): Promise<App[]> {
    return this.prisma.app.findMany(args);
  }
  async findOne<T extends Prisma.AppFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.AppFindUniqueArgs>
  ): Promise<App | null> {
    return this.prisma.app.findUnique(args);
  }
  async create<T extends Prisma.AppCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AppCreateArgs>
  ): Promise<App> {
    return this.prisma.app.create<T>(args);
  }
  async update<T extends Prisma.AppUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AppUpdateArgs>
  ): Promise<App> {
    return this.prisma.app.update<T>(args);
  }
  async delete<T extends Prisma.AppDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.AppDeleteArgs>
  ): Promise<App> {
    return this.prisma.app.delete(args);
  }

  async findAppAdmins(
    parentId: string,
    args: Prisma.UserFindManyArgs
  ): Promise<User[]> {
    return this.prisma.app
      .findUnique({
        where: { id: parentId },
      })
      .appAdmins(args);
  }

  async findCategories(
    parentId: string,
    args: Prisma.CategoryFindManyArgs
  ): Promise<Category[]> {
    return this.prisma.app
      .findUnique({
        where: { id: parentId },
      })
      .categories(args);
  }

  async findGrades(
    parentId: string,
    args: Prisma.GradeFindManyArgs
  ): Promise<Grade[]> {
    return this.prisma.app
      .findUnique({
        where: { id: parentId },
      })
      .grades(args);
  }

  async findTags(
    parentId: string,
    args: Prisma.TagFindManyArgs
  ): Promise<Tag[]> {
    return this.prisma.app
      .findUnique({
        where: { id: parentId },
      })
      .tags(args);
  }
}
